### ISSUE TITLE
svelte-kit not found

### ISSUE THREAD

**Issue by blinry** [HenryLie/svelte-i18n-lingui#5]
Hi, thanks for working on this project! :) When we tried to install it according to the README, the first npm install command fails saying that it cannot find the `svelte-kit` command.

We fixed it by installing the `@sveltejs/kit`, but we had a plain Svelte project before, without Sveltekit. That doesn't seem necessary.

Can you reproduce this?

**Comment by HenryLie** [comment]
Thanks for reporting the issue! 

Indeed, Sveltekit shouldn't be required if you're using this in a plain Svelte project. I think this might be an issue with the `postinstall` script I prepared for development.
Let me try this out and get back to you :)

**Comment by HenryLie** [comment]
This one should also be fixed in v0.1.7. 
Could you confirm this as well?

**Comment by blinry** [comment]
Yes, looks perfect! Thanks! :tada:
