### ISSUE TITLE
Argument of type 'number' is not assignable to type 'string'

### ISSUE THREAD

**Issue by blinry** [HenryLie/svelte-i18n-lingui#7]
When I use a construction like this:

```javascript
let i = 1
let s = gt`${i}`
```

the TypeScript language server will complain: `Argument of type 'number' is not assignable to type 'string'`

I can fix it with

```javascript
let s = gt`${i.toString()}`
```

But it'd be nice if that would be handled automatically – would that be possible?

Thanks for working on this library! :tada:

**Comment by HenryLie** [comment]
Hey, thanks for reporting this too! 

You're right, the parameter is currently only typed as string, where number should also be allowed 👍 
Seems like it should accept only `string` or `number` then, as I don't think any other type make sense to be passed in as-is?

**Comment by HenryLie** [comment]
Hi @blinry, this issue should be fixed in v0.1.7. Could you confirm this? 😄

**Comment by blinry** [comment]
Fix confirmed as working!
@HenryLie confirmed as awesome! :D

And I think I also don't think any other types are missing.
